ASC_HOME=$(HOME)/Projects/ASC-1.5

include $(ASC_HOME)/makefile.config

# =================
# STREAM INFOMATION
# =================

STREAM_INPUTS=8
STREAM_OUTPUTS=8

# ==============
# DEFAULT CONFIG
# ==============

DEFAULT = -DOPT="THROUGHPUT" -DOPTMODE="0" -DOPTTYPE="0"

# ================
# SOFTWARE TARGETS
# ================

CXX_TARGET0 = asctest
CXX_SRC0 = asctest.cxx

# ===============
# RUN EXPERIMENTS
# ===============

#RUN0 = --ALT -DDEGREE="1;2;3;4;5" -DOPT="AREA;LATENCY;THROUGHPUT"

#RUN0 = --ALT -DOUTPUT_BW="14;16;18;20" -DOPT="LATENCY"

#RUN0 = --ALT -DOUTPUT_BW="20" -DBWMODE="0;1" -DOPT="LATENCY"

RUN0 = --ALT -DOPTMODE="0;1" -DOPTTYPE="0;1" -DOPT="THROUGHPUT"

RUN1 = --SW-SIM="asctest.dat" -DDEGREE="1;2;3;4;5" -DOPT="AREA;LATENCY;THROUGHPUT"
RUN2 = --FPGA-SIM="asctest.dat" -DDEGREE="1;2;3;4;5" -DOPT="AREA;LATENCY;THROUGHPUT"

# ======
# GRAPHS
# ======

GRAPHS0 = -XOPTMODE -XOPTTYPE

#GRAPHS0 = -XTOTAL_BITS
#GRAPHS1 = -XTOTAL_BITS

# ================
# REGRESSION TESTS
# ================

TEST0 = --SW-FPGA="asctest.dat" --tolerance=0.2 -DDEGREE="1;2;3;4;5" -DOPT="AREA;LATENCY;THROUGHPUT"
TEST1 = --SW-FPGA="asctest.dat" --tolerance=0.05 -DDEGREE="1;2;3" -DOPT="LATENCY"

# ===
# END
# ===



include $(ASC_HOME)/makefile.std

.PRECIOUS: %.script
