include ../makefile.tests

ifeq ($(OMODE),ad)
OPT_MODE= -r sim -p ad_cpp -m area_cpp
else
OPT_MODE= -r affine -p affine_cpp -m area_cpp
endif

#OPT_MODE= -r affine -p ad_cpp 

R_FLAGS= 16


#ASC_HOME= $(HOME)/Projects/ASC/ASCv1.2
#include $(ASC_HOME)/makefile.config



#BITSIZE_HOME=$(HOME)/Projects/bitsize

BITSIZE_HOME=$(HOME)/Projects/bitsize

include $(BITSIZE_HOME)/makefiles/makefile.bitsize

TESTBWS=14 16 18 20


test_error: test_error.cpp
	g++ -o $@ $^ -I$(ASA_HOME) -ldl

error_lib:
	g++ -fPIC -shared -Wl,-soname,libcostfunc.so -o libcostfunc.so cost_func.cpp -I$(ASA_HOME)


#include $(ASC_HOME)/makefile.std
