# $Id: makefile.config,v 1.1 2004/07/21 19:13:59 amag97 Exp $
# $Author: amag97 $

ARFLAGS=crus

DEBUG_INFO=yes
PROFILE_INFO=no

CC=g++
CP=cp -f
AR=ar
RM=rm -f

ifeq ( $(shell $(CC) --version | grep "Linux"),)
PLATFORM=cygwin
else
PLATFORM=linux
endif

ifeq ($(DEBUG_INFO),yes)
CFLAGS+= -g
endif


ifeq ($(PROFILE_INFO),yes)
CFLAGS+= -pg
endif

