# $Author: amag97 $
# $Id: makefile.config,v 1.10 2006/04/28 17:12:09 amag97 Exp $

# BitSize config file 


#Default optimisation method
c_dir := $(shell pwd | sed -e 's/\/.*\///')

PLHOME:= $(BITSIZE_HOME)/plfiles

ASA_HOME := $(BITSIZE_HOME)/MyASA


ifndef OPT_MODE
OPT_MODE=-r sim -p autodiff
endif

ifdef R_FLAGS
RUN_TIME_FLAGS=-R $(R_FLAGS)
endif

#Default execution mode
EXEC_ONCE=yes

# Default Options
BS_GRAPH_GEN=yes
BS_DEBUG_INFO=yes
BS_PROFILE_INFO=no

CXXDEFINES= -D _BITSIZE_

ifeq ($(BS_DEBUG_INFO),yes)
DBFLAGS += -g
CXXDEFINES+=  -D _BITSIZE_DEBUG_
endif

ifeq ($(BS_PROFILE_INFO),yes)
DBFLAGS += -pg
endif

ifeq ($(BS_GRAPH_GEN),yes)
CXXDEFINES+= -D _GRAPH_GEN
endif


DEBUG_OUT=false


ifeq ($(EXEC_ONCE),yes)
CXXDEFINES+= -D EXEC_ONCE_FLAG="true"
else
CXXDEFINES+= -D EXEC_ONCE_FLAG="false"
endif


BS_LIBDIRS+= -L $(BITSIZE_HOME)/ad_bitsize -L $(ASA_HOME)
BS_INCDIRS+= -I $(BITSIZE_HOME)/ad_bitsize -I $(ASA_HOME)


BS_CFLAGS= $(CPPDEFINES) $(DBFLAGS) $(CXXDEFINES) $(BS_INCDIRS) $(CFLAGS) $(CFLAGS_IN)

BS_LIB=bitsize

BS_LIB_PATH= $(BITSIZE_HOME)/ad_bitsize/lib$(BS_LIB).a

DEFAULT_SLIB_PATH=.

#BS_LFLAGS= $(BS_LIBDIRS) -l$(BS_LIB) -lmyasa $(DBFLAGS) -ldl -Wl,-rpath,$(DEFAULT_SLIB_PATH)
BS_LFLAGS= $(BS_LIBDIRS) -l$(BS_LIB) -lmyasa $(DBFLAGS)   -Wl,-rpath,$(DEFAULT_SLIB_PATH)


# Default stream target
STREAM_TARGET= stream.exe

# PreProcessing Scripts
BITSIZE2ASC=$(BITSIZE_HOME)/plfiles/bs2asc.pl
BITSIZE2ASC2=$(BITSIZE_HOME)/plfiles/bs2asc2.pl


#PostProcessing Scripts
ASC2BITSIZE=$(BITSIZE_HOME)/plfiles/asc2bs.pl

PLHOME:= $(BITSIZE_HOME)/plfiles

#PLATFORM=cygwin

# Main tools
CC=g++
CP=cp -f
AR=ar
RM=rm -f
PERL=perl


#XPWR Settings


XPWR_CURRENT_UNIT=uA
XPWR_POWER_UNIT=uW
XPWR_FREQ_UNIT=KHz

# Extra tools
CHECKDOTTY=$(shell which dotty 2> /dev/null)

ifeq ($(CHECKDOTTY),)
DOTTY=/c/Program\ Files/ATT/Graphviz/bin/dotty 
else
DOTTY=dotty
endif


#Hardware Generation Options

BS_DATA_FILE=asctest.dat

BS_DATA_EXCH=bs_data_exch.dat

BS_XFLOW_OPT_FILE=bitsize.opt

BS_DESIGN_NAME=bitsize_test

BS_TB_NAME=bitsize_tb

NETGEN_OPTIONS=-rpw 100 -tpw 0 -ar Structure -xon true -w -ofmt vhdl 
MAP_OPTIONS=-cm area -pr b -k 4 -c 100 -tx off 


BS_MAP_EFFORT=std
BS_PAR_EFFORT=std

BS_BITGEN_OPT=-g LCK_cycle:5 -g Match_cycle:Auto -g DONE_cycle:6  -g GTS_cycle:4 -g GWE_cycle:Done -g HswapenPin:Pulldown -g M0Pin:Pulldown -g CclkPin:PullNone -g ProgPin:PullNone -g DriveDone:Yes -g TdiPin:PullNone -d -w

BS_SIM_CYCLES=200
SIM_TIME=1000ns
BS_PERIOD_MUL=2;

FPGA_ARCH=VIRTEX2
FPGA_PART=XC2V1000
FPGA_PACKAGE=BG575
FPGA_SPEED_GRADE=-6

SYNPLICIY_REQ_FREQ=100.0

BS_REQ_PERIOD=10ns

GEN_XCORE=true

#Xilinx Core Settings
BS_XCORE_MUL_RPM=true


BS_XCORE_CMUL_RPM=true

BS_XCORE_ADD_RPM=true

BS_XCORE_REG_RPM=true

BS_XCORE_CTR_RPM=true


MPPR_MODE=0

MPPR_LIMIT=1

#Hardware Specific
INPUT_ROM_DEPTH=1024
INPUT_ROM_WIDTH=32


ifeq ($(BENCH_MODE),empty) 
BLANK_ROMS=true
else
BLANK_ROMS=false
endif

XOR_TREE_WIDTH=32
